In [47]:
##PyTorch


In [4]:
# prompt: import torch

import torch
torch.__version__

'2.4.1+cu121'

In [5]:
scalar=torch.tensor(42)
scalar

tensor(42)

In [6]:
scalar.ndim #no of dimansion

0

In [14]:
vector=torch.tensor([7,2])

In [15]:
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 2])
1
torch.Size([2])


In [19]:
matrix= torch.tensor([[1,2],[3,4]])
print(matrix.shape)
print(matrix.ndim)

torch.Size([2, 2])
2


In [20]:
matrix= torch.tensor([[1,2,3],[3,4]])
print(matrix.shape)
print(matrix.ndim)

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [25]:
random_tensor =torch.rand(3,3,3)
print(random_tensor)

tensor([[[0.5951, 0.0681, 0.1462],
         [0.0212, 0.5716, 0.6938],
         [0.1831, 0.7712, 0.9512]],

        [[0.0657, 0.8086, 0.7961],
         [0.1730, 0.2297, 0.9008],
         [0.9108, 0.5009, 0.6799]],

        [[0.8363, 0.6317, 0.2715],
         [0.6740, 0.3716, 0.0603],
         [0.6439, 0.3186, 0.9571]]])


In [26]:
zero_tensor=torch.zeros(size=(3,3,3))
print(zero_tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [27]:
one_tensor=torch.ones(size=(3,3,3))
print(one_tensor)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [32]:
tensor2 =torch.ones_like(random_tensor)
print(tensor2)
print(tensor2.dtype)#datatype

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.float32


In [30]:
a=torch.arange(start= 0, end= 100,step=10)
print(a)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [34]:
float_16_tensor=torch.tensor([1,2,3],dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [35]:
#torch.mannual_seed(1234)-> to save random tensor

In [36]:
# ndim,shape,datatype,device

In [37]:
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [38]:
#operations
tensor=torch.tensor([1,2,3])
print(tensor +10)#tensor.add(tensor,10)
print(tensor -10)#tensor.sub(tensor,10)
print(tensor *10)#tensor.mul(tensor ,10)
print(tensor*tensor)#elementwise
print(tensor@tensor)#matrix multiplication
print(torch.matmul(tensor,tensor))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([1, 4, 9])
tensor(14)
tensor(14)


In [46]:
tensor_A=torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
tensor_B=torch.tensor([[7,10],[8,11],[9,12]],dtype=torch.float32)
#torch.matmul(tensor_A,tensor_B)
torch.matmul(tensor_A,tensor_B.T)#torch.mm() or @
print(tensor_A.shape)
print(tensor_B.shape)
print(tensor_A)
print(tensor_B)

torch.Size([3, 2])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
